#!/bin/bash
# Writes ganesha.conf for the add-on options to stdout. Log lines go to stderr.
# Usage: gen-config.sh [options.json] [root]   (root prefixes the folder existence check; tests only)
set -e

CONFIG_PATH=${1:-/data/options.json}
ROOT=${2:-/}

# Read the authorized_ips array and join with commas for Ganesha
AUTHORIZED_IPS=$(jq --raw-output '.authorized_ips | join(",")' "$CONFIG_PATH")

# Read the export_folders array
EXPORT_FOLDERS=$(jq --raw-output '.export_folders[]' "$CONFIG_PATH")

echo "[NFS] Authorized IPs: ${AUTHORIZED_IPS}" >&2
echo "[NFS] Export folders: $(jq --raw-output '.export_folders | join(", ")' "$CONFIG_PATH")" >&2

cat <<EOF
###################################################
#     NFS-Ganesha Config Generated by Addon       #
###################################################

NFS_CORE_PARAM
{
    NFS_Port = 2049;
    NFS_Protocols = 4;
    Enable_NLM = false;
    Enable_RQUOTA = false;
}

NFSv4
{
    Grace_Period = 60;
    # Use numeric IDs to avoid ID mapping issues
    Only_Numeric_Owners = true;
}

EXPORT_DEFAULTS
{
    Squash = All_Squash;
    Anonymous_Uid = 0;
    Anonymous_Gid = 0;
}

NFS_KRB5
{
    Active_krb5 = false;
}

LOG {
    Default_Log_Level = WARN;
    COMPONENTS {
        TIRPC = FATAL;
        NFS_CB = FATAL;
        INIT = FATAL;
        DISPATCH = FATAL;
    }
}
EOF

# Add Exports based on user selection
ID=10

while IFS= read -r FOLDER; do
    DIR="/$FOLDER"

    if [ -d "${ROOT%/}$DIR" ]; then
        echo "[NFS] Exporting: $DIR" >&2

        cat <<EOF

EXPORT
{
    Export_Id = $ID;
    Path = "$DIR";
    Pseudo = "$DIR";
    FSAL { Name = VFS; }
    Access_Type = None;
    CLIENT
    {
        Clients = $AUTHORIZED_IPS;
        Protocols = 4;
        Access_Type = RW;
    }
}
EOF
        ID=$((ID+1))
    else
        echo "[WARN] Directory $DIR does not exist, skipping..." >&2
    fi
done <<< "$EXPORT_FOLDERS"
