#!/bin/bash
set -e

CONFIG_PATH=/data/options.json

# Read the authorized_ips array and join with commas for Ganesha
AUTHORIZED_IPS=$(jq --raw-output '.authorized_ips | join(",")' $CONFIG_PATH)

# Read the export_folders array
EXPORT_FOLDERS=$(jq --raw-output '.export_folders[]' $CONFIG_PATH)

echo "[NFS] Starting NFS-Ganesha (Debian Mode)..."
echo "[NFS] Authorized IPs: ${AUTHORIZED_IPS}"
echo "[NFS] Export folders: $(jq --raw-output '.export_folders | join(", ")' $CONFIG_PATH)"

# 1. Start DBUS
echo "[NFS] Starting D-Bus..."
mkdir -p /var/run/dbus
if [ -e /var/run/dbus/pid ]; then rm /var/run/dbus/pid; fi
dbus-daemon --system --fork

# 2. Start RPCBIND (but don't fail if it doesn't work)
if rpcinfo -p localhost > /dev/null 2>&1; then
    echo "[INFO] rpcbind is already running on host."
else
    echo "[INFO] Starting rpcbind..."
    mkdir -p /run/rpcbind
    rpcbind || echo "[WARN] rpcbind failed to start, continuing anyway..."
fi

# 3. Build Ganesha Configuration
CONF="/etc/ganesha/ganesha.conf"
mkdir -p /etc/ganesha

cat > $CONF <<EOF
###################################################
#     NFS-Ganesha Config Generated by Addon       #
###################################################

NFS_CORE_PARAM
{
    NFS_Port = 2049;
    NFS_Protocols = 3,4;

    # Enable mount protocol (needed for showmount)
    Mount_Path_Pseudo = true;
}

NFSv4
{
    Grace_Period = 60;
    # Use numeric IDs to avoid ID mapping issues
    Only_Numeric_Owners = true;
}

EXPORT_DEFAULTS
{
    Access_Type = RW;
}

LOG {
    # limit log clutter
    Default_Log_Level = WARN;
}
EOF

# 4. Add Exports based on user selection
ID=10

while IFS= read -r FOLDER; do
    DIR="/$FOLDER"
    
    if [ -d "$DIR" ]; then
        echo "[NFS] Exporting: $DIR"
        
        cat >> $CONF <<EOF

EXPORT
{
    Export_Id = $ID;
    Path = "$DIR";
    Pseudo = "$DIR";
    Access_Type = RW;
    
    # Map all users to root for full access
    Squash = All_Squash;
    Anonymous_Uid = 0;
    Anonymous_Gid = 0;
    
    CLIENT
    {
        Clients = $AUTHORIZED_IPS;
        Access_Type = RW;
    }

    FSAL {
        Name = VFS;
    }
}
EOF
        ID=$((ID+1))
    else
        echo "[WARN] Directory $DIR does not exist, skipping..."
    fi
done <<< "$EXPORT_FOLDERS"

echo "[DEBUG] ===== Generated Ganesha Config ====="
cat $CONF
echo "[DEBUG] ===================================="

# 5. Launch Ganesha with the "Log & Tail" trick
LOGFILE="/var/log/ganesha.log"
touch $LOGFILE
tail -F $LOGFILE &

echo "[NFS] Launching Ganesha Daemon..."

/usr/bin/ganesha.nfsd -F -L $LOGFILE -f $CONF
