#!/bin/bash
# NFS-Ganesha addon launcher with extensive diagnostics.
# NOTE: intentionally NOT using `set -e` for the whole script so that a single
# failing diagnostic command cannot silently abort startup. Ganesha's own exit
# code is captured and reported explicitly at the end.
set -uo pipefail

CONFIG_PATH=/data/options.json

log()  { echo "[NFS $(date -u '+%H:%M:%S')] $*"; }
rule() { echo "======================================================================"; }

rule
log "NFS-Ganesha addon starting (verbose diagnostics enabled)"
rule

# ---------------------------------------------------------------------------
# 0. Environment / host diagnostics
# ---------------------------------------------------------------------------
log "Ganesha version:"
/usr/bin/ganesha.nfsd -v 2>&1 | sed 's/^/    /' || log "  (could not query version)"
log "Package version: $(dpkg-query -W -f='${Version}' nfs-ganesha 2>/dev/null || echo unknown)"
log "Kernel: $(uname -a)"
log "User: $(id)"
log "Container hostname: $(hostname)"

log "Network interfaces / addresses:"
( ip -o addr show 2>/dev/null || ifconfig -a 2>/dev/null ) | sed 's/^/    /'

log "Listening sockets BEFORE start (looking for 111/2049 conflicts):"
( ss -tlnup 2>/dev/null | grep -E ':111|:2049' || echo "    none on 111/2049" ) | sed 's/^/    /'

log "rpcbind / portmapper registrations (host):"
( rpcinfo -p 2>/dev/null || echo "    rpcinfo unavailable" ) | sed 's/^/    /'

# ---------------------------------------------------------------------------
# 1. Read options
# ---------------------------------------------------------------------------
if [ ! -f "$CONFIG_PATH" ]; then
  log "FATAL: $CONFIG_PATH not found - cannot read addon options"
  exit 1
fi

log "Raw options.json:"
( jq '.' "$CONFIG_PATH" 2>/dev/null || cat "$CONFIG_PATH" ) | sed 's/^/    /'

AUTHORIZED_IPS=$(jq --raw-output '.authorized_ips | join(",")' "$CONFIG_PATH")
EXPORT_FOLDERS=$(jq --raw-output '.export_folders[]' "$CONFIG_PATH")

# Log verbosity is configurable via the "log_level" addon option (declared in
# config.yaml, so it is settable from the HA UI). Valid Ganesha levels:
# NULL, FATAL, MAJ, CRIT, WARN, EVENT, INFO, DEBUG, MID_DEBUG, FULL_DEBUG.
# Falls back to EVENT (normal operation) when the option is absent; raise to
# DEBUG/FULL_DEBUG to troubleshoot.
LOG_LEVEL=$(jq --raw-output '.log_level // "EVENT"' "$CONFIG_PATH")

log "Authorized IPs: ${AUTHORIZED_IPS}"
log "Export folders: $(jq --raw-output '.export_folders | join(", ")' "$CONFIG_PATH")"
log "Ganesha log level: ${LOG_LEVEL}"

# ---------------------------------------------------------------------------
# 2. Start D-Bus (Ganesha uses it for its management interface)
# ---------------------------------------------------------------------------
log "Starting D-Bus..."
mkdir -p /var/run/dbus
[ -e /var/run/dbus/pid ] && rm -f /var/run/dbus/pid
if dbus-daemon --system --fork; then
  log "D-Bus started."
else
  log "WARNING: dbus-daemon failed to start (continuing; Ganesha may still run)."
fi

# ---------------------------------------------------------------------------
# 3. Build Ganesha configuration
# ---------------------------------------------------------------------------
CONF="/etc/ganesha/ganesha.conf"
mkdir -p /etc/ganesha

cat > "$CONF" <<EOF
###################################################
#     NFS-Ganesha Config Generated by Addon       #
###################################################

NFS_CORE_PARAM
{
    NFS_Port = 2049;
    NFS_Protocols = 4;
    Enable_NLM = false;
    Enable_RQUOTA = false;
    # Ganesha 6.x calls prctl(PR_SET_IO_FLUSHER), which needs CAP_SYS_RESOURCE.
    # HA addons don't get that capability, so the call returns EPERM and the
    # daemon aborts (exit 2). Allow the failure so startup continues.
    Allow_Set_Io_Flusher_Fail = true;
}

NFSv4
{
    Grace_Period = 60;
    # Use numeric IDs to avoid ID mapping issues
    Only_Numeric_Owners = true;
}

EXPORT_DEFAULTS
{
    Squash = All_Squash;
    Anonymous_Uid = 0;
    Anonymous_Gid = 0;
}

NFS_KRB5
{
    Active_krb5 = false;
}

# Verbose logging: single global level, no per-component muting, so nothing is
# hidden. Lower via the addon "log_level" option once things are healthy.
LOG {
    Default_Log_Level = ${LOG_LEVEL};
    Format {
        EPOCH = false;
        HOSTNAME = false;
        PROGNAME = true;
        PID = true;
        THREAD_NAME = true;
        FILE_NAME = true;
        LINE_NUM = true;
        FUNCTION_NAME = true;
        COMPONENT = true;
        LEVEL = true;
    }
}
EOF

# ---------------------------------------------------------------------------
# 4. Add exports
# ---------------------------------------------------------------------------
ID=10
EXPORT_COUNT=0

while IFS= read -r FOLDER; do
    [ -z "$FOLDER" ] && continue
    DIR="/$FOLDER"

    if [ -d "$DIR" ]; then
        log "Exporting: $DIR (Export_Id=$ID)"
        log "  contents:"; ls -la "$DIR" 2>&1 | head -10 | sed 's/^/      /'
        log "  backing fs:"; stat -f "$DIR" 2>&1 | sed 's/^/      /'

        cat >> "$CONF" <<EOF

EXPORT
{
    Export_Id = $ID;
    Path = "$DIR";
    Pseudo = "$DIR";
    FSAL { Name = VFS; }
    Access_Type = None;
    CLIENT
    {
        Clients = $AUTHORIZED_IPS;
        Protocols = 4;
        Access_Type = RW;
    }
}
EOF
        ID=$((ID + 1))
        EXPORT_COUNT=$((EXPORT_COUNT + 1))
    else
        log "WARNING: directory $DIR does not exist, skipping export."
    fi
done <<< "$EXPORT_FOLDERS"

if [ "$EXPORT_COUNT" -eq 0 ]; then
    log "WARNING: no valid export folders were found. Ganesha will start with no exports."
fi

rule
log "Generated ganesha.conf:"
sed 's/^/    /' "$CONF"
rule

# libtirpc may try to reach rpcbind; ensure the socket dir exists.
mkdir -p /run/rpcbind

# ---------------------------------------------------------------------------
# 5. Launch Ganesha in the foreground, logging to STDOUT so the HA addon log
#    captures everything. -N sets the startup log level too (before the config
#    LOG block is parsed), so early failures are visible as well.
# ---------------------------------------------------------------------------
log "Launching Ganesha daemon (foreground, log level ${LOG_LEVEL}, log -> stdout)..."
rule

# -F : foreground   -L STDOUT : log to stdout   -N : initial log level
# -f : config file
/usr/bin/ganesha.nfsd -F -L STDOUT -N NIV_"${LOG_LEVEL}" -f "$CONF"
GANESHA_RC=$?

# ---------------------------------------------------------------------------
# 6. Post-mortem (only reached if Ganesha exits)
# ---------------------------------------------------------------------------
rule
log "Ganesha exited with code: ${GANESHA_RC}"
log "Post-mortem diagnostics:"
log "  listening sockets now:"
( ss -tlnup 2>/dev/null | grep -E ':111|:2049' || echo "    none on 111/2049" ) | sed 's/^/    /'
log "  dmesg tail (nfs/rpc):"
( dmesg 2>/dev/null | grep -iE 'nfs|rpc|ganesha' | tail -15 || echo "    (dmesg unavailable)" ) | sed 's/^/    /'
rule

exit "$GANESHA_RC"
